### ISSUE TITLE
no Android Permissions identifier?

### ISSUE THREAD

**Issue by Severed-Infinity** [bolav/fuse-contacts#1]
below is the following error I get when trying to run the android side of the project, your library works perfectly fine on iOS but this issue is baffling me. At first I thought it was a general issue with android but was able to run a separate project on android.

`project/fuse_modules/bolav/fuse-contacts/ContactsImpl.Android.uno(62.3): E3102: There is no identifier named 'Permissions' accessible in this scope. Did you mean 'Permissions' (as in Android.Base.Permissions) or 'Permissions' (as in Android.java.security.Permissions)? For example, try adding 'using Android.Base;' to the top of the code file. Could you be missing a package reference?`

**Comment by eksperts** [comment]
@Severed-Infinity this issue should go away when the changes in the currently open pull request are reviewed and merged to master.
The right solution was to refactor the Android `AuthorizeImpl()` method to use correct approach to request permissions, which now has been implemented.
As you correctly identified, there was no issue with this on iOS.
